### PR TITLE
Refactor durationInSeconds method to round the result

### PR DESCRIPTION
**Pull request by seabasss**

### CODE REVIEW

**Comment by rodrigopedra** [comment]
@dbpolito shouldn't this always round up?

If the result is about 40.1 seconds, it is more than 40 seconds. 

It is like doing math for man-power on a task, like construction. As there one can't hire a fraction of a man, the planning is always rounded up.

**Comment by seabasss** [comment]
> @dbpolito shouldn't this always round up?
> 
> If the result is about 40.1 seconds, it is more than 40 seconds.
> 
> It is like doing math for man-power on a task, like construction. As there one can't hire a fraction of a man, the planning is always rounded up.

Good point. If you check duration across apps like Finder, QuickTime, iTunes, and Logic, you’ll notice they handle rounding differently—some round up, others round to closest second. Even Apple apps aren’t consistent (I’ve checked them all).

For royalties, payment is typically based on full seconds. But with 0.4 seconds, rounding down would result in no payment. In our app, we chose to round anything under 1 second up to 1, and anything over to the nearest second, though I see the case for always rounding up.

Which approach is best? I think that depends on the case and need. Closest second may be closer to the truth when adding up 100 tracks. At least, rounding is better than casting to int, which simply chops the decimals (=rounding down), which we can agree on is wrong.

**Comment by seabasss** [comment]
@rodrigopedra Maybe more than you want to know, but for fun I exported a 1 sec 23 frame audio file and got the following durations:
iTunes: 0:02
QuickTime: 0:02
Finder sidebar inspector and CMD+I window: 0:02
Spacebar Finder Preview: 0:01
Logic Export window: 0:01

Some results in iTunes with different audio file lengths:
1 frame: 0:00
10 frames: 0:00
12 frames: 0:01
23 frames: 0:01
1 sec 1 frame: 0:01
1 sec 10 frames: 0:01
1 sec 23 frames: 0:02

When I asked a group of music editors, they voted for accuracy, but never 0 if there are frames, so we settled on what I described above: round up if below a second and closest second if it’s above.

That being said. I’m not opposed to always rounding up.

**Comment by rodrigopedra** [comment]
Thanks, @seabasss, for the insights. Let's see what the maintainers think of it.

In our use case, we sync timeframes between the backend and a JavaScript frontend. We have a web-based editor where archivists can cut and tag smaller clips from a longer video.

The HTML's `<video>` element has some weird quirks when seeking for an exact time. When debugging it, we found a note for Firefox saying it is purposely to avoid fingerprinting. 

So we resort to some weird math/conversion hacks to go back and forth seconds and timecodes, including fractional seconds on the frontend, to be as precise as possible.

So far, in a small testing suite, no quirks have been noticed. 

But, I just deployed the new version to production. Maybe in the upcoming days, someone from the archivist team can notice something. But I guess it will be unlikely.

I was mostly worried about consistency. Thanks again for providing such insightful information about this matter.

**Comment by seabasss** [comment]
@rodrigopedra This method has always returned an INT, so fractions of seconds aren’t supported. If frames aren’t a factor, that’s fine, but converting frames to rounded seconds will naturally lose precision. I understand the importance of consistency in your case, though.

Adding an argument to control rounding could be a flexible solution, with a default in one direction. Still, landing on a single, agreed-upon approach might be the best route.

**Comment by rodrigopedra** [comment]
>  so fractions of seconds aren’t supported

I meant on the frontend:

>  including fractional seconds on the frontend

HTML's `<video>` element uses fractions there, then we use some trickery to convert it back and forth timecode. 

From this library, I more interested in the timecode to seconds conversion than the other way around, we use that to set up some widgets on the frontend in advance.

**Comment by seabasss** [comment]
> > so fractions of seconds aren’t supported
> 
> I meant on the frontend:
> 
> > including fractional seconds on the frontend
> 
> HTML's `<video>` element uses fractions there, then we use some trickery to convert it back and forth timecode.
> 
> From this library, I more interested in the timecode to seconds conversion than the other way around, we use that to set up some widgets on the frontend in advance.

When I think of it. A method that returns seconds with fractions wouldn't be a bad method to have.

Is this something that I can PR for? Basically a new `durationInSecondsWithFractions()` method.

And maybe even a `durationInSecondsRoundedUp()` or `durationInSecondsCeil()`.

**Comment by dbpolito** [comment]
i think as much as we give clarity and option is a good thing... maybe we should revert this function and add those options as you said

**Comment by seabasss** [comment]
> i think as much as we give clarity and option is a good thing... maybe we should revert this function and add those options as you said

Reverting the method will still cause the "convert to float" error. However, if the new change could pose issues for current users of the package, it might be better to add new methods instead. Or maybe you meant reverting to just casting to INT, which essentially is rounded down?

In that case, I’d suggest these:

- durationInSecondsRounded()
- durationInSecondsRoundedUp()
- durationInSecondsWithFractions()

I'd be happy to PR this.

**Comment by seabasss** [comment]
@dbpolito @rodrigopedra What do you guys think of this?

```php
/**
 * Get total duration in seconds based on frame count, rounded down to the nearest second
 *
 * @return int
 */
public function durationInSeconds() : int
{
    return (int) ($this->frameCount / $this->frameRate);
}

/**
 * Get total duration in seconds based on frame count, rounded to the nearest second
 *
 * @return int
 */
public function durationInSecondsRounded() : int
{
    return (int) round($this->frameCount / $this->frameRate);
}

/**
 * Get total duration in seconds based on frame count, rounded to the nearest second
 * Ensures a minimum of 1 second if frames are present
 *
 * @return int
 */
public function durationInSecondsRoundedMinOne() : int
{
    if ($this->frameCount === 0) {
        return 0;
    }

    return max(1, (int) round($this->frameCount / $this->frameRate));
}

/**
 * Get total duration in seconds based on frame count, rounded up to the nearest second
 *
 * @return int
 */
public function durationInSecondsRoundedUp() : int
{
    return (int) ceil($this->frameCount / $this->frameRate);
}

/**
 * Get total duration in seconds with fractional precision based on frame count
 *
 * @return float
 */
public function durationInSecondsWithFractions() : float
{
    return $this->frameCount / $this->frameRate;
}
```

**Pull request merged**
